import { useEffect, useRef, useState, type ReactNode } from 'react';
import { act, available, loanPayment, newGame, parseSave, PROSPECTS, SAVE_KEY, unlocks, type Action, type Game } from './engine.js';
import './business-game.css';
const cash=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const art=`${import.meta.env.BASE_URL}new-art/`;
function Portrait({id,large=false}:{id:string;large?:boolean}){const index=PROSPECTS.findIndex(p=>p.id===id);return <div className={`portrait ${large?'large':''}`} role="img" aria-label={`Portrait of ${PROSPECTS[index]?.name}`} style={{backgroundImage:`url(${art}portraits.webp)`,backgroundPosition:`${index*50}% center`}}/>;}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={onClose} aria-labelledby="modal-title"><div className="modal-top"><span className="overline">Gateway State · Your decision</span><button className="close" aria-label="Close dialog" onClick={onClose}>×</button></div><h2 id="modal-title">{title}</h2>{children}</dialog>;}
function boot(){let raw:string|null=null;try{raw=localStorage.getItem(SAVE_KEY);return {game:raw?parseSave(raw):newGame(),error:'',recovery:null as string|null};}catch{return {game:newGame(),recovery:raw,error:'Your saved file could not be read. A recovery copy will be kept when you start again. You can export the original from Save options.'};}}
export function BusinessGame(){
  const [initial]=useState(boot),[game,setGame]=useState<Game>(initial.game),[error,setError]=useState(initial.error),[screen,setScreen]=useState<'campus'|'player'|'business'>('campus'),[modal,setModal]=useState<'ledger'|'save'|'review'|'next-season'|null>(null),[pending,setPending]=useState<Action|null>(null),[showResult,setShowResult]=useState(false),[message,setMessage]=useState('');
  const person=PROSPECTS.find(p=>p.id===game.athlete?.prospectId),u=unlocks(game),report=game.report;
  function save(g:Game){try{if(initial.recovery&&!localStorage.getItem(SAVE_KEY+'-recovery'))localStorage.setItem(SAVE_KEY+'-recovery',initial.recovery);localStorage.setItem(SAVE_KEY,JSON.stringify(g));setError('');}catch{setError('Autosave is unavailable. Export your career from Save options before leaving.');}setGame(g);}
  function execute(action:Action){try{const next=act(game,action);save(next);setPending(null);setModal(null);if(action.type==='advance'){setShowResult(true);setMessage('Week settled. Progress saved.');}else{setMessage(action.type==='sign'?`${PROSPECTS.find(p=>p.id===action.id)!.name} has joined Gateway.`:'Decision saved. Your commitments have been updated.');setScreen('campus');}}catch(e){setError(e instanceof Error?e.message:'That action could not be completed.');setPending(null);}}
  function exportSave(raw=false){const text=raw?initial.recovery:JSON.stringify(game);if(!text)return;const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`gateway-${game.season}-week-${game.week}${raw?'-recovery':''}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const review=(action:Action)=>{setError('');setPending(action);};
  const advance=()=>game.week===12?setModal('next-season'):execute({type:'advance'});
  const loan=game.business.loan;
  return <div className="business-game"><header className="brand-header"><a className="brand" href={import.meta.env.BASE_URL} aria-label="College Legends home"><span className="crest">G</span><span>COLLEGE LEGENDS<small>BUILD SOMETHING THAT LASTS.</small></span></a><div className="header-right"><span className="build-label">EARLY PLAYABLE</span><button className="save-button" onClick={()=>setModal('save')}>Save options</button></div></header>
    <div className="game-layout"><aside className="campus-scene"><img src={`${art}campus.webp`} alt="Original illustrated small football campus with brick athletic offices, a weight room, practice field and modest bleachers"/><div className="scene-shade"/><div className="scene-title"><span className="overline">Saint Louis · Fictional college football</span><h1>Gateway State</h1><p>Small beginnings.<br/>A program worth believing in.</p></div><div className="scene-footer"><span>EST. 1964</span><span>THE ARCHERS</span></div></aside>
    <div className="game-panel"><div className="season-strip"><div><span className="overline">{game.athlete?`SEASON ${game.season}`:'YOUR FIRST DAY'}</span><strong>{game.bankrupt?'Program insolvent':game.athlete?(game.week===12?'Season complete':`Week ${game.week+1} · ${game.wins}–${game.losses}`):'A fresh start.'}</strong></div><button className={`cash-chip ${game.business.cash<0?'negative':''}`} onClick={()=>setModal('ledger')}><span>{game.business.cash<0?'Cash shortfall':'School cash'} ↗</span><strong>{cash(game.business.cash)}</strong></button></div>
    {error&&<div className="alert" role="alert">{error}</div>}{game.business.shortfallWeeks>0&&!game.bankrupt&&<div className="alert" role="alert">Obligations exceed cash. {3-game.business.shortfallWeeks} more weekly shortfall{game.business.shortfallWeeks===1?'s':''} will close the program. Review available financing before advancing.</div>}
    {game.athlete&&!game.bankrupt&&<nav aria-label="Your program"><button aria-current={screen==='campus'?'page':undefined} onClick={()=>{setScreen('campus');setShowResult(false);}}>Campus</button><button aria-current={screen==='player'?'page':undefined} onClick={()=>{setScreen('player');setShowResult(false);}}>Your player</button>{u.sponsor&&<button aria-current={screen==='business'?'page':undefined} onClick={()=>{setScreen('business');setShowResult(false);}}>Business</button>}</nav>}
    <main>
    {game.bankrupt?<section className="opening"><span className="overline">END OF THIS RUN</span><h2>The bills outlasted<br/>the opportunity.</h2><p>You ended three consecutive weeks unable to cover your obligations. New credit cannot rescue this program.</p><div className="paper">{game.business.entries.slice(-5).map((e,i)=><div className="money-row" key={i}><span>{e.label}</span><strong>{cash(e.amount)}</strong></div>)}</div><p className="hint">Your run remains saved until you choose to restart. Export it to keep the record.</p><button className="primary" onClick={()=>setModal('save')}>Review or start again</button></section>:
    !game.athlete?<section className="opening"><div className="chapter">01 <span>MAKE YOUR FIRST BET</span></div><h2>Who do you<br/>believe in?</h2><p>Your team needs its next quarterback. Your coaches handle the rest. Pick one player to build around.</p><div className="prospects">{PROSPECTS.map(p=><button className="prospect" key={p.id} onClick={()=>review({type:'sign',id:p.id})}><Portrait id={p.id}/><span className="prospect-copy"><span className="overline">{p.description}</span><strong>{p.name}</strong><span>{p.assessment}</span><b>{cash(p.fee)} <small>+ {cash(p.weekly)}/week</small></b></span><span aria-hidden="true" className="arrow">↗</span></button>)}</div><p className="hint">No guaranteed stars. No perfect information.<br/>Your first investment starts a longer story.</p></section>:
    showResult&&report?<section className="opening"><div className="chapter">{String(game.week).padStart(2,'0')} <span>{report.score?'SATURDAY, RESOLVED':'THE NEXT CHAPTER'}</span></div><h2>{report.title}</h2>{report.score&&<div className="scoreboard"><div><span>Gateway</span><strong>{report.score[0]}</strong></div><span>—</span><div><span>{report.opponent}</span><strong>{report.score[1]}</strong></div></div>}<p>{report.detail}</p><div className="paper"><div className="money-row"><span>Net cash this advance</span><strong className={report.net>=0?'gain':'loss'}>{cash(report.net)}</strong></div>{report.score&&<><div className="money-row"><span>Development</span><strong>+{report.growth.toFixed(2)} ability</strong></div>{u.merch&&<div className="money-row"><span>Jerseys sold</span><strong>{report.sales}</strong></div>}</>}</div>{report.unlocked.map(x=><div className="unlock" key={x}><span>NEW OPPORTUNITY</span><strong>{x}</strong></div>)}<button className="primary" onClick={()=>{setShowResult(false);setScreen(report.unlocked.length?'business':'campus');}}>Back to your program →</button></section>:
    screen==='player'?<section className="opening"><div className="player-heading"><Portrait id={person!.id} large/><div><span className="overline">YOUR FIRST SIGNING · QB</span><h2>{person!.name}</h2><p>No. {person!.number} · Gateway Archers</p></div></div><div className="paper"><div className="money-row"><span>Current ability</span><strong>{game.athlete.ability.toFixed(1)}</strong></div><div className="money-row"><span>Growth this season</span><strong className="gain">+{(game.athlete.ability-game.athlete.startAbility).toFixed(1)}</strong></div><div className="money-row"><span>Local recognition</span><strong>{game.athlete.popularity<25?'Emerging':game.athlete.popularity<50?'Recognized':'Local favorite'}</strong></div><div className="money-row"><span>Player earnings to date</span><strong>{cash(game.athlete.earnings)}</strong></div><div className="money-row"><span>Ongoing player agreement</span><strong>{cash(person!.weekly)}/week</strong></div></div><h3>The scout’s first impression</h3><p>{person!.assessment} His ultimate ceiling remains unknown. Staff and facilities improve development opportunities; they cannot promise success.</p><p className="hint">This first build follows one player. Full rosters, eligibility, transfers and wellbeing scenarios are later work.</p></section>:
    screen==='business'?<section className="opening"><div className="chapter">02 <span>GROW WITH INTENTION</span></div><h2>Opportunity has<br/>a price.</h2><p>These decisions are optional. Your existing arrangements keep running when you advance.</p>
      <section className="opportunity"><span className="overline">LOCAL SPONSORSHIP</span><h3>{game.sponsor?'A partner for this season.':'Your first local partner.'}</h3>{game.sponsor?<p>{game.sponsor==='local'?'Gateway Community Bank · $8,000 per game week.':'Northbank Motors · $17,000 for each win.'} Ends with this season.</p>:<><p>Dependable income or a bet on winning?</p><div className="choice-row"><button onClick={()=>review({type:'sponsor',deal:'local'})}>Guaranteed<strong>$8K / game week</strong></button><button onClick={()=>review({type:'sponsor',deal:'wins'})}>Performance<strong>$17K / win</strong></button></div></>}</section>
      {u.merch&&<section className="opportunity"><span className="overline">PLAYER MERCHANDISE</span><h3>The No. {person!.number} collection.</h3><p>{game.stock} jerseys in stock. Sell for $60; $12 goes to your player. Unsold stock ties up cash.</p><div className="choice-row"><button onClick={()=>review({type:'stock',units:300})}>Order 300<strong>$9,000 upfront</strong></button><button onClick={()=>review({type:'stock',units:1000})}>Order 1,000<strong>$30,000 upfront</strong></button></div></section>}
      {u.coach&&<section className="opportunity"><span className="overline">COACHING INVESTMENT</span><h3>{game.coach?'Marcus Bell is on staff.':'A coach who develops talent.'}</h3><p>Marcus Bell · $80K transition cost, then $1,500/week. Better development support, without guaranteed stars.</p>{!game.coach&&<button className="secondary" onClick={()=>review({type:'coach'})}>Compare the commitment →</button>}</section>}
      {u.facility&&<section className="opportunity"><span className="overline">FACILITY INVESTMENT</span><h3>{game.facility==='basic'?'A stronger foundation.':game.facility==='building'?'Construction is underway.':'The new equipment is ready.'}</h3><p>{game.facility==='building'?`${Math.max(0,game.buildAt-game.tick)} calendar weeks until completion.`:'$240K upfront. Eight-week construction. $250/week upkeep after completion. Improves development, not the underlying talent ceiling.'}</p>{game.facility==='basic'&&<button className="secondary" onClick={()=>review({type:'facility'})}>Review project →</button>}</section>}
      {u.loan&&<section className="opportunity"><span className="overline">FINANCING</span><h3>{loan?'Your loan commitment.':'Borrow against tomorrow.'}</h3>{loan?<><p>{cash(loan.balance)} principal outstanding · {loan.paymentsLeft} payments left.</p><p>{loan.paymentsLeft?`${cash(loan.payment)} next calendar week. ${cash(loan.interestPaid)} interest paid.`:'Repaid. Additional credit is unavailable in this build.'}</p></>:<><p>$150K loan · 12% annual interest · 52 weekly payments of about {cash(loanPayment(150000,.12,52))}. One credit line; no endless refinancing.</p><button className="secondary" onClick={()=>review({type:'loan'})}>Review loan terms →</button></>}</section>}
      <p className="next-unlock">AROUND THE CORNER <span>{available(game)}</span></p></section>:
    <section className="opening"><div className="chapter">YOUR PROGRAM <span>{game.week===0?'READY FOR WEEK ONE':'KEEP BUILDING'}</span></div><h2>{game.week===0?'One signing.\nA beginning.':'Every week\nleaves a mark.'}</h2><button className="featured-player" onClick={()=>setScreen('player')}><Portrait id={person!.id}/><span><small>THE PLAYER YOU BELIEVED IN</small><strong>{person!.name}</strong><span>{game.athlete.ability.toFixed(1)} ability · {game.athlete.popularity<25?'Finding his feet':'Building a following'}</span></span><b aria-hidden="true">↗</b></button><p>Your coaches are preparing the team. You decide when to move forward.</p>{u.sponsor&&!game.sponsor&&<button className="new-business" onClick={()=>setScreen('business')}><small>NEW OPPORTUNITY</small><strong>A local sponsor wants to meet. ↗</strong></button>}<button className="primary advance" onClick={advance}>{game.week===12?'Review the offseason':'Advance to Saturday'} <span>→</span></button><p className="next-unlock">AROUND THE CORNER <span>{available(game)}</span></p><div className="small-stats"><span><strong>{game.fans.toLocaleString()}</strong> local fans</span><span><strong>{game.coach?'Developer':'Inherited'}</strong> coaching staff</span><span><strong>{game.facility==='basic'?'Modest':game.facility==='building'?'Building':'Improved'}</strong> facilities</span></div><p className="hint">Early playable · 12-game seasons with automatic offseason settlement. Extended rosters, conference deals and media markets are not built yet.</p></section>}
    </main><div className="saved-status" role="status">{message||'Progress saves on this device after every decision.'}</div></div></div>
    {pending&&<Modal title={pending.type==='sign'?`Back ${PROSPECTS.find(p=>p.id===pending.id)!.name}?`:pending.type==='loan'?'A loan is a commitment.':'Make this investment?'} onClose={()=>setPending(null)}>{pending.type==='sign'?(()=>{const p=PROSPECTS.find(p=>p.id===pending.id)!;return <><Portrait id={p.id} large/><p>{p.assessment} Your signing payment is committed immediately. Weekly compensation continues through the offseason.</p><div className="paper"><div className="money-row"><span>Signing payment</span><strong>{cash(p.fee)}</strong></div><div className="money-row"><span>Weekly compensation</span><strong>{cash(p.weekly)}</strong></div><div className="money-row"><span>52-week compensation</span><strong>{cash(p.weekly*52)}</strong></div><div className="money-row"><span>Cash after signing</span><strong>{cash(game.business.cash-p.fee)}</strong></div></div></>;})():pending.type==='loan'?<><p>Receive $150,000 now. Interest accrues weekly at 12% annually on the unpaid principal, with 52 weekly payments of {cash(loanPayment(150000,.12,52))}. Final payment adjusts for rounding.</p><p>Scheduled total is at most {cash(loanPayment(150000,.12,52)*52)}. Payments continue during the offseason. Three consecutive weekly cash shortfalls end the run. The lender will not offer another loan.</p></>:pending.type==='stock'?<p>Commit {cash(pending.units*30)} for {pending.units} jerseys. At $60 per sale and a $12 player share, full sell-through would contribute {cash(pending.units*18)} after inventory cost. Demand is uncertain; sales only occur during game weeks.</p>:pending.type==='coach'?<p>Pay $80,000 now plus $1,500 every calendar week ($78,000/year). The coordinator improves development opportunity and game preparation. His recurring contract cannot yet be cancelled in this early build.</p>:pending.type==='facility'?<p>Pay $240,000 now. Development benefits begin in eight calendar weeks; upkeep is $250/week thereafter. This is equipment investment—the campus illustration will not change in this first build.</p>:<p>{pending.type==='sponsor'&&pending.deal==='local'?'Receive $8,000 each remaining game week, regardless of results.':'Receive $17,000 for each remaining win. A losing week earns nothing.'} No offseason payments. The choice is fixed until next season.</p>}<div className="modal-actions"><button className="secondary" onClick={()=>setPending(null)}>Keep my options open</button><button className="primary" onClick={()=>execute(pending)}>Confirm commitment</button></div></Modal>}
    {modal==='ledger'&&<Modal title="Your money, accounted for." onClose={()=>setModal(null)}><p>Cash includes all settled receipts and obligations. Loan proceeds are financing, not revenue. Negative cash represents obligations you could not cover.</p><div className="paper"><div className="money-row"><span>Opening funds</span><strong>$600,000</strong></div>{game.business.entries.slice(-16).map((e,i)=><div className="money-row" key={i}><span>{e.label}<small>Calendar week {e.tick}</small></span><strong className={e.amount>=0?'gain':'loss'}>{cash(e.amount)}</strong></div>)}<div className="money-row"><span>Current cash / shortfall</span><strong>{cash(game.business.cash)}</strong></div></div><p className="hint">Most recent 16 entries. Full history is retained in your exported save. Operating support and inherited expenses continue automatically.</p></Modal>}
    {modal==='next-season'&&<Modal title="The commitments carry on." onClose={()=>setModal(null)}><p>You finished {game.wins}–{game.losses}. Alumni support of {cash(80000+game.wins*9000)} will arrive, followed by 40 weeks of offseason obligations.</p><p>Your player receives {cash(person!.weekly*40)} over that period. {game.coach?'Your coordinator costs another $60,000.':''} Loan payments and completed-facility upkeep also continue. No ticket, sponsor, or merchandise receipts arrive during the offseason.</p><p className="hint">You may return to Business and assess available financing first. Advancing can result in bankruptcy.</p><div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Back to my program</button><button className="primary" onClick={()=>execute({type:'advance'})}>Settle & open next season</button></div></Modal>}
    {modal==='save'&&<Modal title="Your career stays yours." onClose={()=>setModal(null)}><p>This new game uses its own save. Your old College Legends career is separate.</p><div className="save-actions"><button className="secondary" onClick={()=>exportSave()}>Export this career</button>{initial.error&&<button className="secondary" onClick={()=>exportSave(true)}>Export unreadable original</button>}<label className="import-label">Import a career<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const loaded=parseSave(await file.text());save(loaded);setModal(null);setShowResult(false);setScreen('campus');}catch{setError('Import failed. Your existing career was not changed.');}}}/></label><details><summary>Start over</summary><p>This replaces only the new business-game save. Export first if you want to keep it.</p><button className="danger" onClick={()=>{save(newGame());setModal(null);setScreen('campus');setShowResult(false);setMessage('A new beginning.');}}>Replace this career</button></details><a href={`${import.meta.env.BASE_URL}?legacy=1`}>Open the previous game</a></div></Modal>}
  </div>;
}
