import {describe,it,expect} from 'vitest';
import {start,schedule,act,plan,advance,table,draft,core} from './core.js';
describe('core player demo',()=>{
it('schedules every team once per week with no repeat opponents',()=>{const games=schedule();expect(games).toHaveLength(96);for(let w=1;w<=12;w++){const ids=games.filter(m=>m.week===w).flatMap(m=>[m.home,m.away]);expect(new Set(ids).size).toBe(16);}for(let t=0;t<16;t++){const opponents=games.filter(m=>m.home===t||m.away===t).map(m=>m.home===t?m.away:m.home);expect(new Set(opponents).size).toBe(12);}});
it('limits core roster and charges exact commitments',()=>{let g=start(42);const initial=g.cash;for(let i=0;i<5;i++)g=act(g,'sign','recruit'+i);expect(core(g)).toHaveLength(5);expect(g.cash).toBe(initial-core(g).reduce((s,p)=>s+p.cost,0));expect(()=>act(g,'sign','recruit5')).toThrow();});
it('resolves development with costs, capacity and separate media effects',()=>{let g=act(start(42),'sign','recruit0');const before=core(g)[0]!.ability;g=plan(g,{player:'recruit0',kind:'Media',specialist:1,facility:1,partner:'',weeks:2,hard:false});expect(()=>plan(g,{player:'recruit0',kind:'Technique',specialist:0,facility:0,partner:'',weeks:2,hard:false})).toThrow();g=advance(advance(g));expect(core(g)[0]!.ability).toBe(before);expect(core(g)[0]!.fame).toBeGreaterThan(10);expect(g.projects).toHaveLength(0);});
it('simulates records, weekly honors, final awards and a real playoff winner',()=>{let g=act(start(99),'sign','recruit2');for(let w=0;w<12;w++)g=advance(g);expect(g.ended).toBe(false);expect(table(g).every(t=>t.wins+t.losses===12)).toBe(true);expect(table(g).reduce((s,t)=>s+t.wins,0)).toBe(96);expect(g.awards.filter(a=>a.week>0)).toHaveLength(24);expect(g.awards.filter(a=>a.week===0)).toHaveLength(6);expect(g.matches.filter(m=>m.week===13)).toHaveLength(2);g=advance(advance(g));const final=g.matches.find(m=>m.week===14)!;expect(final.hs).not.toBeNull();expect(final.hs).not.toBe(final.as);expect(g.news[0]).toContain('championship');expect(draft(g).every(p=>p.year>=3)).toBe(true);expect(g.cash).toBe(2000000+g.ledger.reduce((s,l)=>s+l.amount,0));const year=g.year;g=act(g,'next');expect(g.year).toBe(year+1);expect(g.week).toBe(0);});
it('preserves saves and produces repeatable results',()=>{const g=act(start(777),'sign','recruit0');expect(advance(JSON.parse(JSON.stringify(g)))).toEqual(advance(g));});
it('can fail from exhausted cash and does not erase loan liability',()=>{let g=act(start(55),'sign','recruit0');g.cash=1;g.matches[0]!.home=1;g.matches[0]!.away=0;g=advance(g);expect(g.ended).toBe(true);expect(()=>act(g,'loan')).toThrow();});
});
