export const KEY='college-legends-core-v1';
export type Position='QB'|'HB'|'WR'|'FS'|'EDGE';
export type Player={id:string;name:string;position:Position;team:number;year:number;ability:number;ceiling:number;scouted:boolean;fame:number;fatigue:number;mood:number;want:string;cost:number;points:number;last:number;yards:number;td:number;stops:number;};
export type Match={week:number;home:number;away:number;hs:number|null;as:number|null};
export type Project={player:string;kind:string;specialist:number;facility:number;partner:string;weeks:number;left:number;hard:boolean;cost:number};
export type Game={version:1;seed:number;year:number;week:number;cash:number;players:Player[];matches:Match[];projects:Project[];news:string[];awards:{year:number;week:number;title:string;player:string}[];ledger:{label:string;amount:number}[];units:number[];staff:number[];loan:boolean;ended:boolean;};
export const teams=['Gateway','Pine Coast','Iron Valley','North Bay','Redwood','Capital State','Lake Erie','Mountain Tech','Prairie State','Bluegrass','Twin Rivers','Gulf Atlantic','Desert State','Cedar Ridge','Westhaven','Crossroads'];
export const specialists=[{name:'Campus staff',cost:0,quality:1},{name:'Avery Cole · technique specialist',cost:16000,quality:1.65},{name:'Jordan Vale · performance coach',cost:26000,quality:1.9}];
export const facilities=[{name:'Campus facilities',cost:0,quality:1},{name:'Regional performance lab',cost:12000,quality:1.3},{name:'Elite training center',cost:30000,quality:1.5}];
export const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function random(seed:number,key:string){let h=seed;for(const c of key)h=Math.imul(h^c.charCodeAt(0),16777619);h=Math.imul(h^(h>>>16),2246822507);h=Math.imul(h^(h>>>13),3266489909);return ((h^(h>>>16))>>>0)/4294967296;}
export function schedule():Match[]{const out:Match[]=[];for(let w=0;w<5;w++)for(let i=0;i<8;i++)out.push({week:w+1,home:w%2?8+(i+w)%8:i,away:w%2?i:8+(i+w)%8,hs:null,as:null});for(let c=0;c<2;c++){let ring=[0,1,2,3,4,5,6,7];for(let w=0;w<7;w++){for(let i=0;i<4;i++){const a=ring[i]!+c*8,b=ring[7-i]!+c*8;out.push({week:w+6,home:w%2?a:b,away:w%2?b:a,hs:null,as:null});}ring=[ring[0]!,ring[7]!,...ring.slice(1,7)];}}return out;}
function player(id:string,name:string,position:Position,team:number,ability:number,year:number,seed:number):Player{return{id,name,position,team,ability,year,ceiling:Math.min(99,ability+5+Math.floor(random(seed,id+'upside')*23)),scouted:false,fame:10,fatigue:0,mood:80,want:['A patient developer','The spotlight','A winning program'][Math.floor(random(seed,id)*3)]!,cost:Math.round((ability-40)*1700),points:0,last:0,yards:0,td:0,stops:0};}
export function start(seed=Date.now()):Game{const players:Player[]=[];const names=['Miles Ellis','Jalen Reed','Nico Cruz','Theo Banks','Andre Moss','Caleb Stone','Isaiah Lake','Eli Carter','Dante King'];const pos:Position[]=['QB','HB','FS','WR','EDGE','QB','WR','HB','FS'];names.forEach((n,i)=>players.push(player('recruit'+i,n,pos[i]!,-1,58+i*3,i%3+1,seed)));for(let t=1;t<16;t++)for(let j=0;j<5;j++)players.push(player(`r${t}-${j}`,`${['Amari','Noah','Malik','Owen','Julian'][j]} ${['Price','Brooks','Wells','Hayes','Grant','Ford','West','Reed','Hill','Cole','Davis','Bell','Ward','Cook','Gray'][t-1]}`,(['QB','HB','WR','FS','EDGE'] as Position[])[j]!,t,61+Math.floor(random(seed,`skill${t}${j}`)*28),1+(t+j)%4,seed));return{version:1,seed,year:2027,week:0,cash:2000000,players,matches:schedule(),projects:[],news:['Choose the first player to build your program around. Your supporting units and baseline staff are funded; you control the growth budget.'],awards:[],ledger:[],units:[74,66,70,68],staff:[0,0,0],loan:false,ended:false};}
export const core=(g:Game)=>g.players.filter(p=>p.team===0);
export function table(g:Game){return teams.map((name,id)=>{const games=g.matches.filter(m=>m.hs!==null&&(m.home===id||m.away===id));const wins=games.filter(m=>m.home===id?m.hs!>m.as!:m.as!>m.hs!).length;const conf=games.filter(m=>m.week<=12&&Math.floor(m.home/8)===Math.floor(m.away/8));return{id,name,wins,losses:games.length-wins,conf:conf.filter(m=>m.home===id?m.hs!>m.as!:m.as!>m.hs!).length,diff:games.reduce((s,m)=>s+(m.home===id?m.hs!-m.as!:m.as!-m.hs!),0)};}).sort((a,b)=>b.wins-a.wins||b.diff-a.diff||a.id-b.id);}
export const race=(g:Game)=>g.players.filter(p=>p.team>=0).slice().sort((a,b)=>b.points-a.points||b.ability-a.ability);
export const draft=(g:Game)=>g.players.filter(p=>p.team>=0&&p.year>=3).slice().sort((a,b)=>(b.ability+b.points*.025)-(a.ability+a.points*.025));
function post(g:Game,label:string,amount:number){g.cash+=amount;g.ledger.push({label:`${g.year} W${g.week} · ${label}`,amount});}
function spend(g:Game,label:string,amount:number){if(g.cash<amount)throw Error('Not enough available cash.');post(g,label,-amount);}
export function act(current:Game,type:string,id='',value=0):Game{const g=structuredClone(current);if(g.ended)throw Error('This career has ended. Start a new program to try again.');const p=g.players.find(x=>x.id===id);if(type==='sign'){if(p&&core(g).some(q=>q.position===p.position))throw Error('Choose one focus player per position in this demo.');if(!p||p.team!==-1||core(g).length>=5||g.week>=12)throw Error('Recruit up to five core players before the postseason.');spend(g,`${p.name} · annual institutional commitment`,p.cost);p.team=0;g.news.unshift(`${p.name} joins Gateway. Wants: ${p.want.toLowerCase()}.`);}else if(type==='scout'){if(!p||p.scouted)throw Error('Report already available.');spend(g,'Independent scouting report',8000);p.scouted=true;}else if(type==='rest'){if(!p||p.team!==0)throw Error('Select a core player.');if(g.projects.some(x=>x.player===id))throw Error('Finish the current project before scheduling recovery.');g.projects.push({player:id,kind:'Recovery',specialist:0,facility:0,partner:'',weeks:1,left:1,hard:false,cost:0});}else if(type==='unit'){spend(g,'Unit coaching and equipment investment',80000);g.units[value]=Math.min(95,g.units[value]!+4);}else if(type==='staff'){if(g.staff[value]===1)throw Error('Specialist already hired.');spend(g,['Head coach','Offensive coordinator','Defensive coordinator'][value]+' · annual upgrade',value===0?180000:100000);g.staff[value]=1;}else if(type==='loan'){if(g.loan)throw Error('One bridge loan per season.');g.loan=true;post(g,'University bridge financing · 10% annual interest',300000);}else if(type==='next'){if(g.week!==14)throw Error('Finish this season first.');if(g.loan)post(g,'Bridge principal and annual interest',-330000);if(g.cash<100000){g.ended=true;g.news.unshift('The board has ended your tenure: operating reserves fell below $100,000.');return g;}g.year++;g.week=0;g.loan=false;g.matches=schedule();g.projects=[];g.staff=[0,0,0];for(const q of g.players){q.year++;q.points=0;q.last=0;q.yards=0;q.td=0;q.stops=0;q.fatigue=0;if(q.team===0){if(q.year>4){g.news.unshift(`${q.name} graduates. A new core-player place is open.`);q.team=-2;}else{post(g,`${q.name} · annual renewal`, -q.cost);}}if(q.team>0&&q.year>4){q.year=1;q.ability=62+Math.floor(random(g.seed,q.id+g.year)*20);q.ceiling=Math.min(99,q.ability+15);q.name=q.name.split(' ')[0]+' '+['Young','Turner','James','Scott'][g.year%4];}}for(let i=0;i<5;i++)g.players.push(player(`new${g.year}${i}`,`${['Micah','Zion','Cole','Ty','Devin'][i]} ${['Walsh','Green','Ross','Shaw','Dean'][g.year%5]}`,(['QB','HB','WR','FS','EDGE'] as Position[])[i]!,-1,60+Math.floor(random(g.seed,`${g.year}${i}`)*22),1,g.seed));if(g.cash<0)g.ended=true;}return g;}
export function plan(current:Game,project:Omit<Project,'left'|'cost'>):Game{const g=structuredClone(current),p=core(g).find(x=>x.id===project.player);if(!p)throw Error('Choose a recruited player.');if(g.week>=12)throw Error('New projects reopen next season.');if(g.projects.some(x=>x.player===p.id)||g.projects.length>=3)throw Error('Three project slots; one active project per player.');if(project.weeks>12-g.week)throw Error('Choose a shorter project to finish before the postseason.');if(project.partner&&(project.partner===p.id||!core(g).some(x=>x.id===project.partner)))throw Error('Choose another core player as a partner.');const cost=(specialists[project.specialist]!.cost+facilities[project.facility]!.cost)*project.weeks/2+(project.kind==='Commercial'?30000:5000);spend(g,`${p.name} · ${project.kind} project`,cost);g.projects.push({...project,left:project.weeks,cost});return g;}
export function advance(current:Game):Game{const g=structuredClone(current);if(!core(g).length||g.week>=14||g.ended)throw Error('Recruit a core player first, or begin the next season.');g.week++;g.news=[];for(const p of g.players)p.last=0;for(const job of g.projects){const p=g.players.find(x=>x.id===job.player)!;if(job.kind==='Recovery'){p.fatigue=Math.max(0,p.fatigue-35);p.mood=Math.min(100,p.mood+8);}else if(job.kind==='Media'){p.fame=Math.min(100,p.fame+4*specialists[job.specialist]!.quality*facilities[job.facility]!.quality);p.fatigue=Math.min(100,p.fatigue+3);if(p.want==='The spotlight')p.mood=Math.min(100,p.mood+3);}else if(job.kind!=='Commercial'){const quality=specialists[job.specialist]!.quality*facilities[job.facility]!.quality;const partner=g.players.find(x=>x.id===job.partner);const fit=partner&&((p.position==='QB'&&partner.position==='WR')||(p.position==='HB'&&partner.position==='QB')||(['FS','EDGE'].includes(p.position)&&['FS','EDGE'].includes(partner.position)))?1.2:1;p.ability=Math.min(p.ceiling,p.ability+.65*quality*fit*(job.hard?1.35:1)*(1+g.staff[0]!*.15));p.fatigue=Math.min(100,p.fatigue+(job.hard?14:6));p.mood=Math.max(0,p.mood+(p.want==='A patient developer'?(job.hard?-4:2):0));}job.left--;if(job.left===0){if(job.kind==='Commercial'){const receipts=Math.round((18000+p.fame*1800)*(1+(specialists[job.specialist]!.quality-1)*.3+(facilities[job.facility]!.quality-1)*.4)*(0.6+random(g.seed,p.id+g.year+g.week)));post(g,`${p.name} · school campaign receipts`,receipts);g.news.push(`${p.name}'s campaign returns ${money(receipts)} to the school. Athlete appearance compensation of ${money(Math.round(receipts*.15))} is paid separately by the partner.`);p.fatigue=Math.min(100,p.fatigue+8);}else g.news.push(`${p.name} completed ${job.kind.toLowerCase()}.`);}}
g.projects=g.projects.filter(x=>x.left>0);const strength=(id:number)=>{if(id===0)return g.units.reduce((a,b)=>a+b)/4+core(g).reduce((s,p)=>s+(p.ability-65)*.25-p.fatigue*.035+(p.mood-80)*.015,0)+g.staff.reduce((a,b)=>a+b)*2;const ps=g.players.filter(p=>p.team===id);return ps.reduce((s,p)=>s+p.ability,0)/ps.length;};
for(const m of g.matches.filter(x=>x.week===g.week)){const r=random(g.seed,`${g.year}-${g.week}-${m.home}`);m.hs=Math.max(7,Math.round(25+(strength(m.home)-strength(m.away))*.7+(r-.5)*28+2));m.as=Math.max(7,Math.round(24+(strength(m.away)-strength(m.home))*.7+(random(g.seed,`${g.year}-${g.week}-${m.away}away`)-.5)*28));if(m.hs===m.as)m.hs+=3;for(const p of g.players.filter(x=>x.team===m.home||x.team===m.away)){const score=p.team===m.home?m.hs:m.as;const won=p.team===m.home?m.hs>m.as:m.as>m.hs;const form=.65+random(g.seed,`${g.year}${g.week}${p.id}`)*.7;const effective=p.ability*(1-p.fatigue*.003)*(.85+p.mood*.0015)*form;const offense=['QB','HB','WR'].includes(p.position);const yards=Math.round(effective*(p.position==='QB'?3.1:p.position==='HB'?1.35:1.2));const td=Math.max(0,Math.floor(score/7*(p.position==='HB'?.35:.65)));const stops=Math.round(effective/(p.position==='FS'?9:16));p.yards+=offense?yards:0;p.td+=offense?td:0;p.stops+=offense?0:stops;p.last=offense?yards/12+td*5+(won?5:0):stops*3+(won?8:0);p.points+=p.last;p.fame=Math.min(100,p.fame+p.last*.13);if(p.team===0){p.fatigue=Math.max(0,p.fatigue-4);p.mood=Math.max(0,Math.min(100,p.mood+(p.want==='A winning program'?(won?4:-5):won?2:-1)));}}if(m.home===0||m.away===0){g.news.unshift(`${teams[m.home]} ${m.hs} — ${teams[m.away]} ${m.as}`);if(g.week<=12){post(g,'Net weekly football operations after baseline funding',-140000);if(m.home===0){const attendance=Math.min(22000,Math.round(6500+core(g).reduce((s,p)=>s+p.fame,0)*35+table(g).find(x=>x.id===0)!.wins*450));post(g,`${attendance.toLocaleString()} fans · admissions and concession share`,attendance*34);}}}}
for(const defense of [false,true]){const winner=g.players.filter(p=>p.last>0&&(['FS','EDGE'].includes(p.position)===defense)).sort((a,b)=>b.last-a.last)[0];if(winner)g.awards.push({year:g.year,week:g.week,title:defense?'Defensive player of the week':'Offensive player of the week',player:winner.id});}
if(g.week===12){const ranked=table(g);g.matches.push({week:13,home:ranked[0]!.id,away:ranked[3]!.id,hs:null,as:null},{week:13,home:ranked[1]!.id,away:ranked[2]!.id,hs:null,as:null});const rankedPlayers=race(g);for(const pos of ['National Player', 'QB','HB','WR','FS','EDGE']){const winner=rankedPlayers.find(p=>pos==='National Player'||p.position===pos)!;g.awards.push({year:g.year,week:0,title:pos==='National Player'?'Founders Trophy':`${pos} of the Year`,player:winner.id});}g.news.push('The regular season is complete. Annual awards are final; four teams advance to the playoff.');}
if(g.week===13){const winners=g.matches.filter(m=>m.week===13).map(m=>m.hs!>m.as!?m.home:m.away);g.matches.push({week:14,home:winners[0]!,away:winners[1]!,hs:null,as:null});}if(g.week===14){const final=g.matches.find(m=>m.week===14)!;g.news.unshift(`${teams[final.hs!>final.as!?final.home:final.away]} wins the national championship.`);if(g.cash<100000)g.news.push('The board requires $100,000 in reserves at the season review.');}if(g.cash<0){g.ended=true;g.news.unshift('Cash has run out. The board ends your tenure.');}return g;}
