import { useEffect, useRef, useState, type ReactNode } from 'react';
import { CampusWorld } from './CampusWorld.js';
import { campaigns, decide, ENTERPRISE_KEY, homeDates, homeOpponent, matchLimit, packagePrice, restoreEnterprise, startEnterprise, type Decision, type Enterprise } from './enterprise.js';
import './enterprise.css';
const money=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function Sheet({title,children,close}:{title:string;children:ReactNode;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return <dialog className="enterprise-sheet" ref={ref} onCancel={close} aria-labelledby="enterprise-sheet-title"><button className="sheet-close" onClick={close} aria-label="Close details">×</button><h2 id="enterprise-sheet-title">{title}</h2>{children}</dialog>;}
function boot(){let raw:string|null=null;try{raw=localStorage.getItem(ENTERPRISE_KEY);return {game:raw?restoreEnterprise(raw):startEnterprise(),raw:null as string|null,error:''};}catch{return {game:startEnterprise(),raw,error:'The previous file could not be read. It will be kept as a recovery copy before a new save.'};}}
export function EnterpriseGame(){
 const [initial]=useState(boot),[g,setGame]=useState(initial.game),[error,setError]=useState(initial.error),[sheet,setSheet]=useState<string|null>(null),[paused,setPaused]=useState(false),[status,setStatus]=useState(''),main=useRef<HTMLElement>(null);
 function persist(next:Enterprise){try{if(initial.raw)localStorage.setItem(ENTERPRISE_KEY+'-recovery',initial.raw);localStorage.setItem(ENTERPRISE_KEY,JSON.stringify(next));setError('');setStatus('Progress saved on this device.');}catch{setError('Autosave unavailable. Export this career before closing.');}setGame(next);}
 function choose(d:Decision){try{persist(decide(g,d));requestAnimationFrame(()=>{main.current?.focus({preventScroll:true});if(matchMedia('(max-width: 760px)').matches)main.current?.scrollIntoView({block:'start',behavior:'instant'});});}catch(e){setError(e instanceof Error?e.message:'Decision unavailable.');}}
 const button=(label:string,d:Decision)=> <button className="e-primary" onClick={()=>choose(d)}>{label}<span aria-hidden="true">→</span></button>;
 const report=['campaign-report','match-report'].includes(g.stage);
 function exportCareer(){const url=URL.createObjectURL(new Blob([JSON.stringify(g)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`gateway-enterprise-${g.year}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="enterprise"><header className="e-header"><a href={import.meta.env.BASE_URL}><span className="e-crest">G</span><span>COLLEGE LEGENDS<small>A TOWN. A TEAM. YOUR RESPONSIBILITY.</small></span></a><div><button onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?'Resume life':'Pause motion'}</button><button onClick={()=>setSheet('Your career')}>Save</button></div></header>
 <div className="e-title"><div><span className="e-eyebrow">YOUR FIRST PROGRAM</span><h1>Small school. Big Saturdays.</h1></div><button className="reserve" onClick={()=>setSheet('Operating reserves')}><small>Available reserves ↗</small><strong>{money(g.cash)}</strong></button></div>
 <div className="e-layout"><div className="e-world-column"><CampusWorld game={g} paused={paused} onInspect={setSheet}/><div className="campus-wire"><span className="e-eyebrow">AROUND CAMPUS</span>{g.news.map(n=><p key={n}>{n}</p>)}</div><div className="e-facts"><span><b>{g.year}</b> Season</span><span><b>{homeDates(g)}</b> Home dates</span><span><b>{g.tickets.toLocaleString()}</b> Season packages</span></div></div>
 <main className="e-decision" ref={main} tabIndex={-1}><span className="e-eyebrow">{g.stage==='renewals'?'YOUR FIRST MOVE':g.stage==='annual'?'BEFORE NEXT SEASON':report?'WHAT HAPPENED':'ON YOUR DESK'}</span>
 {error&&<p role="alert" className="e-error">{error}</p>}
 {g.stage==='renewals'&&<><h2>Give them a reason<br/>to come back.</h2><p>You inherited a team, a staff, and a schedule. The ticket office needs a renewal plan. How much will you put behind it?</p><div className="e-context">{homeDates(g)} home games · {money(packagePrice(g))} per season package</div><div className="e-choices">{campaigns.map(c=><button key={c.id} onClick={()=>choose(c.id)} disabled={g.cash<c.cost}><span className="choice-top"><strong>{c.title}</strong><b>{money(c.cost)}</b></span><span>{c.description}</span><small>Initial estimate: {c.range} · demand can disappoint</small></button>)}</div><p className="e-note">Campaign cost is paid immediately. Your staff handles delivery. These are fictional planning estimates, not guaranteed sales.</p></>}
 {report&&<><h2>{g.report.title}</h2><p>{g.report.body}</p><div className={`e-result ${g.report.net<0?'e-negative':''}`}><span>Operating cash change</span><strong>{g.report.net>=0?'+':''}{money(g.report.net)}</strong></div><button className="e-text-button" onClick={()=>setSheet('Operating reserves')}>See the receipts and costs ↗</button>{button(g.stage==='campaign-report'?'Open the gates':'Back to the office','continue')}</>}
 {g.stage==='match'&&<><h2>Saturday belongs<br/>to the town.</h2><p>Gateway hosts {homeOpponent(g)}. Home date {g.match+1} of {matchLimit(g)}. Your coaches prepare the team. Your commercial commitments keep running.</p><div className="e-context">{g.tickets.toLocaleString()} season seats already paid for<br/>Walk-up tickets $28 · event operations $46,000</div>{g.sponsor&&<p className="e-note">Northbank pays $14,000 for this home date’s signage and hospitality rights.</p>}{button('Play the home game','continue')}<p className="e-note">Results use the inherited team, not one star. Attendance depends on renewals, supporter loyalty and weather.</p></>}
 {g.stage==='partner'&&<><h2>Someone noticed<br/>the crowd.</h2><p>Northbank wants the remaining home dates: signage, mentions and hospitality access. Your inherited commercial partner will service the deal.</p><div className="e-context">$14,000 per remaining home game<br/>One season · local banking exclusivity</div>{button('Accept the local partnership','partner')}<button className="e-secondary" onClick={()=>choose('independent')}>Leave the inventory unsold</button><p className="e-note">This is school sponsorship income. Athlete endorsements and conference TV rights are separate.</p></>}
 {g.stage==='schedule'&&<><h2>Next year starts<br/>on this calendar.</h2><p>A larger program has offered a road guarantee for next season. Your university has cleared either option for an open nonconference date.</p><div className="e-choices"><button onClick={()=>choose('away')}><span className="choice-top"><strong>Take the road guarantee</strong><b>$180K</b></span><span>$45K travel allocation. Five home dates next year, smaller season packages and one fewer date for local partners. Payment settles after the road game.</span></button><button onClick={()=>choose('home')}><span className="choice-top"><strong>Keep the home plan</strong><b>6 dates</b></span><span>Preserve the inherited local fixture and its earning opportunities. No guarantee payment; you carry the event costs and attendance risk.</span></button></div><p className="e-note">A future-season commitment, not a last-minute opponent swap. Conference games stay assigned.</p></>}
 {g.stage==='capital'&&<><h2>A gift comes<br/>with a commitment.</h2><p>A donor will contribute $220,000 toward a compact hospitality terrace. The university has approved the project if you provide the remaining $330,000.</p><div className="e-context">Your match: $330,000 now<br/>Upkeep: $4,000 each home date<br/>Bookings are uncertain</div><p>The donor’s gift goes straight to construction. It cannot fund salaries or cover an operating shortfall.</p><button className="e-primary" disabled={g.cash<330000} onClick={()=>choose('build')}>Commit the matching funds <span>→</span></button><button className="e-secondary" onClick={()=>choose('defer')}>Keep our reserves</button><p className="e-note">This small modular project opens by the next home date in the accelerated prototype calendar. The $100K annual reserve requirement still applies.</p></>}
 {g.stage==='annual'&&<><h2>The promises<br/>outlast the season.</h2><p>Your home slate is complete. Settle the $95,000 shared athletics contribution before opening renewals for next year.</p><div className="e-context">Projected reserves after settlement<br/><strong>{money(g.cash-95000+(g.thisYearAway?135000:0))}</strong><br/>University minimum: $100,000</div>{g.thisYearAway&&<p>The road guarantee adds $180,000 and travel costs $45,000 at this settlement.</p>}<p>Next year brings {g.future==='away'?5:6} home dates. Local sponsorship expires. {g.premium?'Hospitality upkeep remains.':''}</p>{button('Settle & open renewals','next')}<p className="e-note">Falling below the disclosed minimum ends your tenure. This prototype has no emergency credit facility.</p></>}
 {g.stage==='ended'&&<><h2>Your tenure<br/>has ended.</h2><p>You finished the year below the university’s $100,000 operating-reserve requirement. The university withdrew your spending authority.</p><div className="e-result e-negative"><span>Reserves remaining</span><strong>{money(g.cash)}</strong></div><p>The commitments were real, even when the expected returns were not. You can inspect the ledger and export this run.</p><button className="e-primary" onClick={()=>setSheet('Your career')}>Review or start again →</button></>}
 <footer className="e-decision-footer"><span role="status">{status||'Your existing team and base budget are already in place.'}</span><button onClick={()=>setSheet('About this build')}>Build notes</button></footer></main></div>
 {sheet&&<Sheet title={sheet} close={()=>setSheet(null)}>
 {sheet==='Operating reserves'?<><p>$600,000 opening operating reserves, plus the settled items below. The approved inherited base budget is separate; this ledger shows incremental commercial activity and the shared contribution.</p><div className="e-ledger">{g.lines.map((l,i)=><div key={i}><span><small>{l.year}</small>{l.label}</span><b>{money(l.amount)}</b></div>)}<div><strong>Available reserves</strong><b>{money(g.cash)}</b></div></div><p>Restricted donor funding: {money(g.grant)} received and {money(g.restrictedSpent)} applied directly to construction. Neither is spendable operating cash.</p></>:
 sheet==='Your career'?<><p>This business-world prototype has its own save. Earlier careers are preserved.</p><button className="e-primary" onClick={exportCareer}>Export career</button><label className="e-import">Import exported career<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{persist(restoreEnterprise(await file.text()));setSheet(null);}catch{setError('Import failed. Your current career was not replaced.');}}}/></label><details><summary>Start a new tenure</summary><p>Export first to keep this run. Only this prototype’s save will be replaced.</p><button className="e-secondary" onClick={()=>{persist(startEnterprise());setSheet(null);}}>Replace this prototype career</button></details></>:
 sheet==='Ticket office'?<><p>Mara Chen leads your inherited ticket team. {g.tickets?`${g.tickets} season packages are committed for ${homeDates(g)} home games.`:'The team is waiting for your renewal campaign decision.'}</p><p>Package receipts arrive before kickoff. Those seats do not create another admission payment on game day.</p></>:
 sheet==='Football grounds'?<><p>Coach Bell and the inherited roster handle practice and games. Supporter traffic and the illustrated crowd change with the business calendar and attendance.</p><p>The figures represent activity, not every ticket holder. Coaching appointments and roster economics are future work.</p></>:
 sheet==='Hospitality terrace'?<><p>The donor-backed terrace adds booking income and $4,000 in upkeep each home date. A quiet season does not cancel that obligation.</p><p>The project used $330,000 of operating reserves and $220,000 of restricted donor funding.</p></>:
 <><p>This playable slice links renewals, home-event economics, local sponsorship, next-season scheduling and restricted capital funding. Monetary values are fictional balancing assumptions.</p><p>The approved inherited budget covers base football operations. The scene shows an illustrated campus with animated activity, rather than a full match simulation. Reduced-motion preferences are respected; motion can also be paused.</p><p>All home dates are playable. Away football results, coach contracts, full roster/NIL accounting, borrowing and conference negotiations are not implemented yet. A road guarantee is settled in the annual review.</p><a href={`${import.meta.env.BASE_URL}?prototype=1`}>Earlier player prototype</a></>}
 </Sheet>}
 </div>;
}
